export type Country = { name: string; iso: string; dial: string; flag: string };

// Common subset covering most countries. Extend as needed.
export const COUNTRIES: Country[] = [
  { name: "Bangladesh", iso: "BD", dial: "880", flag: "🇧🇩" },
  { name: "India", iso: "IN", dial: "91", flag: "🇮🇳" },
  { name: "Pakistan", iso: "PK", dial: "92", flag: "🇵🇰" },
  { name: "Nepal", iso: "NP", dial: "977", flag: "🇳🇵" },
  { name: "Sri Lanka", iso: "LK", dial: "94", flag: "🇱🇰" },
  { name: "Bhutan", iso: "BT", dial: "975", flag: "🇧🇹" },
  { name: "Maldives", iso: "MV", dial: "960", flag: "🇲🇻" },
  { name: "United States", iso: "US", dial: "1", flag: "🇺🇸" },
  { name: "Canada", iso: "CA", dial: "1", flag: "🇨🇦" },
  { name: "United Kingdom", iso: "GB", dial: "44", flag: "🇬🇧" },
  { name: "Australia", iso: "AU", dial: "61", flag: "🇦🇺" },
  { name: "New Zealand", iso: "NZ", dial: "64", flag: "🇳🇿" },
  { name: "United Arab Emirates", iso: "AE", dial: "971", flag: "🇦🇪" },
  { name: "Saudi Arabia", iso: "SA", dial: "966", flag: "🇸🇦" },
  { name: "Qatar", iso: "QA", dial: "974", flag: "🇶🇦" },
  { name: "Kuwait", iso: "KW", dial: "965", flag: "🇰🇼" },
  { name: "Oman", iso: "OM", dial: "968", flag: "🇴🇲" },
  { name: "Bahrain", iso: "BH", dial: "973", flag: "🇧🇭" },
  { name: "Jordan", iso: "JO", dial: "962", flag: "🇯🇴" },
  { name: "Lebanon", iso: "LB", dial: "961", flag: "🇱🇧" },
  { name: "Egypt", iso: "EG", dial: "20", flag: "🇪🇬" },
  { name: "Turkey", iso: "TR", dial: "90", flag: "🇹🇷" },
  { name: "Iran", iso: "IR", dial: "98", flag: "🇮🇷" },
  { name: "Iraq", iso: "IQ", dial: "964", flag: "🇮🇶" },
  { name: "Singapore", iso: "SG", dial: "65", flag: "🇸🇬" },
  { name: "Malaysia", iso: "MY", dial: "60", flag: "🇲🇾" },
  { name: "Indonesia", iso: "ID", dial: "62", flag: "🇮🇩" },
  { name: "Thailand", iso: "TH", dial: "66", flag: "🇹🇭" },
  { name: "Vietnam", iso: "VN", dial: "84", flag: "🇻🇳" },
  { name: "Philippines", iso: "PH", dial: "63", flag: "🇵🇭" },
  { name: "China", iso: "CN", dial: "86", flag: "🇨🇳" },
  { name: "Hong Kong", iso: "HK", dial: "852", flag: "🇭🇰" },
  { name: "Taiwan", iso: "TW", dial: "886", flag: "🇹🇼" },
  { name: "Japan", iso: "JP", dial: "81", flag: "🇯🇵" },
  { name: "South Korea", iso: "KR", dial: "82", flag: "🇰🇷" },
  { name: "Germany", iso: "DE", dial: "49", flag: "🇩🇪" },
  { name: "France", iso: "FR", dial: "33", flag: "🇫🇷" },
  { name: "Italy", iso: "IT", dial: "39", flag: "🇮🇹" },
  { name: "Spain", iso: "ES", dial: "34", flag: "🇪🇸" },
  { name: "Portugal", iso: "PT", dial: "351", flag: "🇵🇹" },
  { name: "Netherlands", iso: "NL", dial: "31", flag: "🇳🇱" },
  { name: "Belgium", iso: "BE", dial: "32", flag: "🇧🇪" },
  { name: "Switzerland", iso: "CH", dial: "41", flag: "🇨🇭" },
  { name: "Austria", iso: "AT", dial: "43", flag: "🇦🇹" },
  { name: "Sweden", iso: "SE", dial: "46", flag: "🇸🇪" },
  { name: "Norway", iso: "NO", dial: "47", flag: "🇳🇴" },
  { name: "Denmark", iso: "DK", dial: "45", flag: "🇩🇰" },
  { name: "Finland", iso: "FI", dial: "358", flag: "🇫🇮" },
  { name: "Ireland", iso: "IE", dial: "353", flag: "🇮🇪" },
  { name: "Poland", iso: "PL", dial: "48", flag: "🇵🇱" },
  { name: "Russia", iso: "RU", dial: "7", flag: "🇷🇺" },
  { name: "Ukraine", iso: "UA", dial: "380", flag: "🇺🇦" },
  { name: "South Africa", iso: "ZA", dial: "27", flag: "🇿🇦" },
  { name: "Nigeria", iso: "NG", dial: "234", flag: "🇳🇬" },
  { name: "Kenya", iso: "KE", dial: "254", flag: "🇰🇪" },
  { name: "Ghana", iso: "GH", dial: "233", flag: "🇬🇭" },
  { name: "Brazil", iso: "BR", dial: "55", flag: "🇧🇷" },
  { name: "Mexico", iso: "MX", dial: "52", flag: "🇲🇽" },
  { name: "Argentina", iso: "AR", dial: "54", flag: "🇦🇷" },
  { name: "Chile", iso: "CL", dial: "56", flag: "🇨🇱" },
];
